/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountingsystem2;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;


/**
 *
 * @author administrator
 */
public class CustomerUpdate extends javax.swing.JFrame {

     int cid3;
    /**
     * Creates new form CustForm
     */
    
    
    
    public CustomerUpdate() {
        initComponents();
        setSize(1300,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnm = new javax.swing.JTextField();
        conm = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        mob = new javax.swing.JTextField();
        sub = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        show1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(cnm);
        cnm.setBounds(500, 50, 400, 80);
        getContentPane().add(conm);
        conm.setBounds(500, 200, 400, 80);
        getContentPane().add(city);
        city.setBounds(500, 350, 400, 80);

        mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobActionPerformed(evt);
            }
        });
        getContentPane().add(mob);
        mob.setBounds(500, 500, 400, 80);

        sub.setText("update");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub);
        sub.setBounds(650, 610, 100, 40);
        getContentPane().add(msg);
        msg.setBounds(60, 10, 200, 20);
        getContentPane().add(id1);
        id1.setBounds(1030, 80, 250, 60);

        show1.setText("show");
        show1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show1ActionPerformed(evt);
            }
        });
        getContentPane().add(show1);
        show1.setBounds(1110, 190, 110, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 20, 120, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("COMPANY NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 170, 150, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CITY");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 310, 110, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PHONE NO.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 470, 130, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1030, 50, 70, 25);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 40, 130, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accountingsystem2/iStock-1148634836-Accounting-banner.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1300, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
      try{
     Connection  con=InitConnection.initcon();
  PreparedStatement ps=con.prepareStatement
   ("update customer set cname=?,cnm=?,city=?,mob=? where cid="+cid3);
       ps.setString(1,cnm.getText());
       ps.setString(2,conm.getText());
       ps.setString(3,city.getText());
       ps.setInt(4,Integer.parseInt(mob.getText()));
      int x=ps.executeUpdate();
      cnm.setText("");
      conm.setText("");
      city.setText("");
      mob.setText("");
      msg.setText(x+ "Data Is Update");
      }catch(Exception tt)
      {System.out.println(tt);}
    }//GEN-LAST:event_subActionPerformed

    private void show1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show1ActionPerformed
       try{
     Connection  con=InitConnection.initcon();
       cid3=Integer.parseInt(id1.getText());
      Statement stm1=con.createStatement();
     ResultSet rs1=stm1.executeQuery
        ("select * from customer where cid="+cid3);
      if(rs1.next())
      {
       cnm.setText(rs1.getString(2));
       conm.setText(rs1.getString(3));
       city.setText(rs1.getString(4));
       mob.setText(rs1.getInt(5)+"");
       }else{
       cnm.setText("Data Not Found");
      }
       }catch(Exception tt)
       {System.out.println(tt);}
    }//GEN-LAST:event_show1ActionPerformed

    private void mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
       IndexPage.main( new String[2]);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField cnm;
    private javax.swing.JTextField conm;
    private javax.swing.JTextField id1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mob;
    private javax.swing.JLabel msg;
    private javax.swing.JButton show1;
    private javax.swing.JButton sub;
    // End of variables declaration//GEN-END:variables
}
