/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accountingsystem2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.Date;

/**
 *
 * @author HP
 */
public class PurchaseReturn extends javax.swing.JFrame {

   int invno,cid1,pid1;
   Connection con=null;
   Vector v1=null;
   Vector v2=null;
   Vector v3=null;
   Vector v4=null;
   Vector v5=null;
   
   public void getdata()
   {
       try
       {
        con=InitConnection.initcon();
        Statement stm=con.createStatement();
        //for invoice no.
        ResultSet rs1=stm.executeQuery("select puid from purchase ");
        v5=new Vector();
        while(rs1.next())
        {
            v5.addElement(rs1.getInt(1));
        }
        //quary for get customer data;
        ResultSet rs2=stm.executeQuery("select cid,cname,city from customer ");
        v1=new Vector();
        v2=new Vector();
        while(rs2.next())
        {
            v1.addElement(rs2.getInt(1));
            cb1.addItem(rs2.getString(2));
            v2.addElement(rs2.getString(3));
        }
        //quary for product data;
        ResultSet rs3=stm.executeQuery("select pid,pname,pprice from product where status=0");
        v3=new Vector();
        v4=new Vector();
        while(rs3.next())
        {
            v3.addElement(rs3.getInt(1));
            cb2.addItem(rs3.getString(2));
            v4.addElement(rs3.getInt(3));
        }
       }catch(Exception tt)
       {System.out.println(tt);}
   }
    public PurchaseReturn() {
        initComponents();
        setSize(1300,700);
        getdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        city = new javax.swing.JTextField();
        pp = new javax.swing.JTextField();
        sub = new javax.swing.JButton();
        home = new javax.swing.JButton();
        qt = new javax.swing.JTextField();
        ta = new javax.swing.JTextField();
        msg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        getContentPane().add(pid);
        pid.setBounds(10, 200, 400, 80);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Setect Custmer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 140, 190, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Product");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(870, 300, 180, 40);

        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(870, 200, 400, 80);

        cb2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb2ItemStateChanged(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(870, 350, 400, 80);
        getContentPane().add(city);
        city.setBounds(10, 350, 400, 80);

        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        getContentPane().add(pp);
        pp.setBounds(10, 500, 400, 80);

        sub.setText("Submit");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });
        getContentPane().add(sub);
        sub.setBounds(590, 600, 130, 50);

        home.setText("home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(120, 40, 130, 40);

        qt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtActionPerformed(evt);
            }
        });
        getContentPane().add(qt);
        qt.setBounds(450, 500, 400, 80);
        getContentPane().add(ta);
        ta.setBounds(870, 500, 400, 80);
        getContentPane().add(msg);
        msg.setBounds(460, 390, 220, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PURCHASE ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 170, 150, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CITY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 320, 80, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PURCHASE PRICE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 470, 170, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("QUANTITY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 470, 140, 25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(870, 460, 170, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accountingsystem2/iStock-1148634836-Accounting-banner.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 1300, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       this.setVisible(false);
       IndexPage.main( new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
      try
      {
          int x=cb1.getSelectedIndex();
          city.setText((String)v2.get(x));
          pid.setText((Integer)v5.get(x)+"");
          cid1=(Integer)v1.get(x);
      }catch(Exception tt)
      {System.out.println(tt);}
    }//GEN-LAST:event_cb1ItemStateChanged

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
         try{
            
            //Connection con=InitConnection.initcon();
            PreparedStatement ps=con.prepareStatement
        ("Insert Into purchaseReturn(invno,custid,pid,pprice,qty,ta,date) values(?,?,?,?,?,?,?)");
                ps.setInt(1,Integer.parseInt(pid.getText()));
                ps.setInt(2,cid1);
                ps.setInt(3,pid1);
                ps.setInt(4,Integer.parseInt(pp.getText()));
                ps.setInt(5,Integer.parseInt(qt.getText()));
                ps.setInt(6,Integer.parseInt(ta.getText()));
                ps.setString(7,new Date().toString());
                int x=ps.executeUpdate();
                 msg.setText(x+"Data is Insert");
                
                }catch(Exception tt)
                {System.out.println(tt);}
    }//GEN-LAST:event_subActionPerformed

    private void cb2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb2ItemStateChanged
        try
      {
          int x=cb2.getSelectedIndex();
          pp.setText((Integer)v4.get(x)+"");
          pid1=(Integer)v3.get(x);
      }catch(Exception tt)
      {System.out.println(tt);}
    }//GEN-LAST:event_cb2ItemStateChanged

    private void qtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtActionPerformed
       int t=Integer.parseInt(pp.getText());
       int j=Integer.parseInt(qt.getText());
       ta.setText(t*j+"");
    }//GEN-LAST:event_qtActionPerformed

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JTextField city;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField qt;
    private javax.swing.JButton sub;
    private javax.swing.JTextField ta;
    // End of variables declaration//GEN-END:variables
}
